$ANSIBLE_VAULT;1.1;AES256
62383337653362336239376230623432326265363562333733316163633861313464313761633065
3665336262376461373833336130613063623830383932300a373939343235376631323536316264
33613332376336346233626365333961363730623935323038616631636166333735643733333734
3538333562343962310a646363643635666330636533333735373766356363623137353136643133
66353735613738623335373061303635323161643631623036326435363432303232
