name: Test Cron Workflow
on:
  schedule:
    - cron: "*/5 * * * *"
    - cron: "*/20 * * * *"
  push:
    branches: 
      - main
      - feature

jobs:
  test-cron-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Test Workflow
        run: |
          ls
          echo "Hello From The Other side"
