# name: cd workflow

on:
  push:
    branches:
      - "main"

jobs:
  cd-workflow-job:
    name: cd workflow
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3.6.0
        with:
        # Create at repo level ; actions secrets 
          username: ${{ secrets.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_PASSWORD }}  # Tocken or password

      - name: Build and push
        uses: docker/build-push-action@v6.18.0 
        with:
          push: true
          tags: dinagamal/java-app:latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1 
        with:
        #must be stored as well as docker username and password
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: deploy to k8s
        run: |-
          aws eks update-kubeconfig --region us-east-2 --name eks
          kubectl apply -f ./k8s/deployment.yaml
