---
- name: First play to create a user
  hosts: managednode2
  tasks:
    - name: Creating user {{user}}
      user:
        name: "{{user}}"
        state: present
      register: user_results
    - debug: var=user_results
    - debug: 
        msg: "{{ansible_enp0s8['ipv4']['address']}}"


