


# install mysql
ubuntu@ip-172-31-42-108:~$ sudo apt update

ubuntu@ip-172-31-42-108:~$ sudo apt install mysql-server

ubuntu@ip-172-31-42-108:~$ sudo systemctl status mysql.service




# This user will manage the exporter service.
$ sudo groupadd --system prometheus
$ sudo useradd -s /sbin/nologin --system -g prometheus prometheus


# Download and install Prometheus MySQL Exporter:
$ curl -s https://api.github.com/repos/prometheus/mysqld_exporter/releases/latest   | grep browser_download_url | grep linux-amd64 |  cut -d '"' -f 4 | wget -qi -

$ tar xvf mysqld_exporter-*.linux-amd64.tar.gz
$ cd mysqld_exporter-*.linux-amd64/
$ chmod +x mysqld_exporter
$ sudo mv mysqld_exporter /usr/local/bin
$ mysqld_exporter --version


# Create Prometheus exporter database user:

$ sudo mysql
mysql> CREATE USER 'mysqld_exporter'@'localhost' IDENTIFIED BY 'StrongPassword' WITH MAX_USER_CONNECTIONS 2;
mysql> GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO 'mysqld_exporter'@'localhost';
mysql> FLUSH PRIVILEGES;
mysql> exit
Bye


#Create database credentials file
$ sudo vim /etc/.mysqld_exporter.cnf
---
[client]
user=mysqld_exporter
password=StrongPassword
---

$ sudo chown root:prometheus /etc/.mysqld_exporter.cnf



$ sudo vim /etc/systemd/system/mysql_exporter.service
---
[Unit]
Description=Prometheus MySQL Exporter
After=network.target
User=prometheus
Group=prometheus

[Service]
Type=simple
Restart=always
ExecStart=/usr/local/bin/mysqld_exporter \
--config.my-cnf /etc/.mysqld_exporter.cnf \
--collect.global_status \
--collect.info_schema.innodb_metrics \
--collect.auto_increment.columns \
--collect.info_schema.processlist \
--collect.binlog_size \
--collect.info_schema.tablestats \
--collect.global_variables \
--collect.info_schema.query_response_time \
--collect.info_schema.userstats \
--collect.info_schema.tables \
--collect.perf_schema.tablelocks \
--collect.perf_schema.file_events \
--collect.perf_schema.eventswaits \
--collect.perf_schema.indexiowaits \
--collect.perf_schema.tableiowaits \
--collect.slave_status \
--web.listen-address=0.0.0.0:9104

[Install]
WantedBy=multi-user.target
---

$ sudo systemctl daemon-reload
$ sudo systemctl start mysql_exporter
$ sudo systemctl enable mysql_exporter
$ sudo systemctl status mysql_exporter



>>>> Go To Prometheus Server

$ sudo vim /etc/prometheus/prometheus.yml
---
  - job_name: "mysql-node"
    static_configs:
      - targets: ["172.31.42.108:9104"]
---

$ sudo systemctl restart prometheus.service








