
- Create User with permission 'AmazonEC2ReadOnlyAccess' --> Create Access Keys 

Update your Prometheus configuration file (prometheus.yml):

---
scrape_configs:
  - job_name: 'example'
    ec2_sd_configs:
      - region: 'us-east-1'
        access_key: 'your-access-key'
        secret_key: 'your-secret-key'
        port: 9100 
---

Restart Prometheus:
$ sudo systemctl restart prometheus.service


Ensure Exporter is Running on EC2 Instances:

launch ec2 with bash script node exporter:
---
#!/bin/bash -e

sudo useradd --no-create-home --shell /bin/false node_exporter

cd /tmp/
wget https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz

tar -xvf node_exporter-1.3.1.linux-amd64.tar.gz
cd node_exporter-1.3.1.linux-amd64

sudo mv node_exporter /usr/local/bin/
sudo chown node_exporter:node_exporter /usr/local/bin/node_exporter

sudo tee /etc/systemd/system/node_exporter.service <<EOF
[Unit]
Description=Node Exporter
After=network.target

[Service]
User=node_exporter
Group=node_exporter
Type=simple
ExecStart=/usr/local/bin/node_exporter

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl start node_exporter
sudo systemctl enable node_exporter
---


If you want to filter ec2 with tags:

---
  - job_name: 'prom-ec2'
    ec2_sd_configs:
      - region: 'us-east-1'
        access_key: 'AKIA...........'
        secret_key: 'W0S...............'
        port: 9100
        filters:
          - name: tag:tittle
            values:
              - prom
---


